# Generated by Django 6.1.1 on 2026-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#ff8a3d', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='target',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='🔥', max_length=10),
        ),
    ]
