from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.dashboard_view, name='dashboard'),
    path('api/dashboard/', views.dashboard_data_view, name='dashboard_data'),
    path('tasks/', views.tasks_view, name='tasks'),
    path('api/tasks/create/', views.task_create_view, name='task_create'),
    path('api/tasks/<int:task_id>/toggle/', views.task_toggle_view, name='task_toggle'),
    path('api/tasks/<int:task_id>/update/', views.task_update_view, name='task_update'),
    path('api/tasks/<int:task_id>/delete/', views.task_delete_view, name='task_delete'),
    path('api/tasks/<int:task_id>/make-main/', views.task_make_main_view, name='task_make_main'),
    path('api/tasks/<int:task_id>/remove-main/', views.task_remove_main_view, name='task_remove_main'),
    path('api/tasks/<int:task_id>/carry-over/', views.task_carry_over_view, name='task_carry_over'),
    path('habits/', views.habits_view, name='habits'),
    path('api/habits/create/', views.habit_create_view, name='habit_create'),
    path('api/habits/<int:habit_id>/toggle/', views.habit_toggle_view, name='habit_toggle'),
    path('api/habits/<int:habit_id>/update/', views.habit_update_view, name='habit_update'),
    path('api/habits/<int:habit_id>/delete/', views.habit_delete_view, name='habit_delete'),
    path('goals/', views.goals_view, name='goals'),
    path('api/goals/create/', views.goal_create_view, name='goal_create'),
    path('api/goals/<int:goal_id>/toggle/', views.goal_toggle_view, name='goal_toggle'),
    path('api/goals/<int:goal_id>/update/', views.goal_update_view, name='goal_update'),
    path('api/goals/<int:goal_id>/delete/', views.goal_delete_view, name='goal_delete'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('calendar/<int:year>/<int:month>/<int:day>/', views.calendar_day_view, name='calendar_day'),
    path('api/events/create/', views.event_create_view, name='event_create'),
    path('api/events/<int:event_id>/delete/', views.event_delete_view, name='event_delete'),
    path('pomodoro/', views.pomodoro_view, name='pomodoro'),
    path('api/pomodoro/save/', views.pomodoro_save_view, name='pomodoro_save'),
    path('api/pomodoro/settings/', views.pomodoro_settings_view, name='pomodoro_settings'),
    path('statistics/', views.statistics_view, name='statistics'),
    path('settings/', views.settings_view, name='settings'),
    path('api/widgets/toggle/', views.widget_toggle_view, name='widget_toggle'),
    path('api/widgets/reorder/', views.widget_reorder_view, name='widget_reorder'),
    path('api/widgets/reset/', views.widget_reset_view, name='widget_reset'),
]
